### Python for babies

In [4]:
 # Calculadora

2 + 2
    

4

In [5]:
3/6

0.5

Lógicas

In [7]:
2 >  5

False

In [8]:
3 == 3

True

In [9]:
4 != 5

True

In [11]:
for n in range(10):
    print (n*2)

0
2
4
6
8
10
12
14
16
18


In [13]:
for n in range(10):
    print (n*2, end = ' ')
# end = ' ' sirve para imprimirlo en horizontal.

0 2 4 6 8 10 12 14 16 18 

In [16]:
for n in range(10):
    if n == 0:
        print('Iniciamos!', n)
    elif 4 < n < 7 :
        print('medias!', n)
    else:
        print('Mezcla', n)
                   
              

Iniciamos! 0
Mezcla 1
Mezcla 2
Mezcla 3
Mezcla 4
medias! 5
medias! 6
Mezcla 7
Mezcla 8
Mezcla 9


## Arreglos


In [1]:
lista = [2 ,4, 5, 6, 7]

In [2]:
lista

[2, 4, 5, 6, 7]

In [4]:
for num in lista:
    print (num, end = ' ')

2 4 5 6 7 

In [5]:
2 in lista

True

In [7]:
3 in lista

False

In [8]:
3 not in lista

True

In [9]:
lista

[2, 4, 5, 6, 7]

In [10]:
import numpy as np

In [17]:
lista_np = np.array(lista)

In [18]:
lista_np

array([2, 4, 5, 6, 7])

In [20]:
lista*3
# como es caracter se triplica la lista 3 veces.

[2, 4, 5, 6, 7, 2, 4, 5, 6, 7, 2, 4, 5, 6, 7]

In [21]:
type(lista_np)

numpy.ndarray

In [22]:
lista_np*3

array([ 6, 12, 15, 18, 21])

In [23]:
lista_np2 = np.array([1, 2, 3, 4, 5])

In [ ]:
plt.plot(x, y, 'D-', label = 'azul')
plt.plot(x, np.array(y)*2), 'rD-', label = 'rojo' )
plt.legend( loc = 'best')
plt.show()

In [14]:
 t = np.linspace(0, 1)

In [15]:
t

array([ 0.        ,  0.02040816,  0.04081633,  0.06122449,  0.08163265,
        0.10204082,  0.12244898,  0.14285714,  0.16326531,  0.18367347,
        0.20408163,  0.2244898 ,  0.24489796,  0.26530612,  0.28571429,
        0.30612245,  0.32653061,  0.34693878,  0.36734694,  0.3877551 ,
        0.40816327,  0.42857143,  0.44897959,  0.46938776,  0.48979592,
        0.51020408,  0.53061224,  0.55102041,  0.57142857,  0.59183673,
        0.6122449 ,  0.63265306,  0.65306122,  0.67346939,  0.69387755,
        0.71428571,  0.73469388,  0.75510204,  0.7755102 ,  0.79591837,
        0.81632653,  0.83673469,  0.85714286,  0.87755102,  0.89795918,
        0.91836735,  0.93877551,  0.95918367,  0.97959184,  1.        ])

In [16]:
for potencia in range(5):
    plt.plot(t, t**potencia, 'x', label = '%s' % potencia)
plt.ylim(ymas = 1.05)
# Sirve para aumentar el num. mostrado en el eje y.
plt.show()

NameError: name 'plt' is not defined