### Python for babies

In [1]:
# Calculadora
2 + 2

4

In [2]:
3/6

0.5

Lógicas

In [4]:
2 > 5

False

In [6]:
3 == 3

True

In [8]:
4 != 5

True

In [10]:
for n in range(10):
    print(n*2)

0
2
4
6
8
10
12
14
16
18


In [11]:
for n in range(10):
    print(n*2, end = " ")

0 2 4 6 8 10 12 14 16 18 

In [14]:
for n in range(10):
    if n == 0:
        print("Iniciamos!", n)
    elif 4<n<7:
        print ("Medias!", n)
    else:
        print ("Mezclas!", n)

Iniciamos! 0
Mezclas! 1
Mezclas! 2
Mezclas! 3
Mezclas! 4
Medias! 5
Medias! 6
Mezclas! 7
Mezclas! 8
Mezclas! 9


### Arreglos

In [16]:
lista = [2, 4, 5, 6, 7]

In [17]:
lista

[2, 4, 5, 6, 7]

In [18]:
for numero in lista:
    print (numero, end = " ")

2 4 5 6 7 

In [19]:
numero

7

In [20]:
2 in lista

True

In [21]:
3 in lista

False

In [22]:
3 not in lista

True

In [24]:
import numpy as np

In [26]:
lista_np = np.array(lista)

In [28]:
lista_np

array([2, 4, 5, 6, 7])

In [30]:
lista*3

[2, 4, 5, 6, 7, 2, 4, 5, 6, 7, 2, 4, 5, 6, 7]

In [31]:
type(lista_np)

numpy.ndarray

In [32]:
lista_np * 3

array([ 6, 12, 15, 18, 21])

In [33]:
lista_np2 = np.array([1, 2, 3, 4, 5])

In [34]:
lista_np2

array([1, 2, 3, 4, 5])

In [35]:
lista_np

array([2, 4, 5, 6, 7])

In [36]:
lista_np * lista_np2

array([ 2,  8, 15, 24, 35])

In [37]:
np.sum(lista_np * lista_np2)

84

In [40]:
np.dot(lista_np2, lista_np)

84

In [41]:
lista_np2 @ lista_np

84

### Para graficar

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
x = [0, 2, 5, 6, 7, 8, 9]
y = [1, 2, 3, 4, 5, 6, 7]

In [ ]:
plt.plot(x,y, "D-", label = "azul")
plt.plot(x,np.array(y)*2, "D-", label = "rojo")
plt.legend(loc="best")
plt.show()

In [ ]:
print "j"

In [ ]:
t = np.linspace (0, 1, 5)

In [ ]:
t

In [ ]:
for potencia in range (5):
    plt.plot(t, t**potencia, "x", label = "%s", % potencia)
plt.ylim(ymax = 1.05)
plt.legend (loc = "best")
plt.show()